const { gitDescribeSync } = require( 'git-describe' );
const { version } = require( "./package.json" );
const { resolve } = require( 'path' );
const { writeFileSync } = require('fs');

const gitInfo = gitDescribeSync( {
    dirtyMark: "-D",
    longSemver: true,
    dirtySemver: false
});

gitInfo.version = version;

const file = resolve( __dirname + "/src", "environments", "version.ts" );
writeFileSync( file,
    `// THIS FILE IS AUTO GENERATED by src/main/javascript/farkle-ui/git-version.js
    /* tslint:disable */
    export const VERSION = ${ JSON.stringify( gitInfo, null, 4 ) };
    /* tlint:enable */`, { encodeing: "utf-8" } );