// THIS FILE IS AUTO GENERATED by src/main/javascript/farkle-ui/git-version.js
    /* tslint:disable */
    export const VERSION = {
    "dirty": false,
    "raw": "b0af46c",
    "hash": "b0af46c",
    "distance": null,
    "tag": null,
    "semver": null,
    "suffix": "b0af46c",
    "semverString": null,
    "version": "0.1.0"
};
    /* tlint:enable */