// THIS FILE IS AUTO GENERATED by src/main/javascript/farkle-ui/git-version.js
    /* tslint:disable */
    export const VERSION = {
    "dirty": false,
    "raw": "",
    "hash": "",
    "distance": null,
    "tag": null,
    "semver": null,
    "suffix": "",
    "semverString": null,
    "version": "0.1.0"
};
    /* tlint:enable */